# To enable the "Sponsor" button on GitHub, uncomment and fill the relevant lines.
# Docs: https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/displaying-a-sponsor-button-in-your-repository

# github: gokhangunduz
# buy_me_a_coffee: gokhangunduz
# custom: ["https://example.com/donate"]
